[target.aarch64-linux-android]
image = "docker.pkg.github.com/meatlink/northstar/aarch64-linux-android:v11"

[target.aarch64-unknown-linux-gnu]
image = "docker.pkg.github.com/meatlink/northstar/aarch64-unknown-linux-gnu:v11"

[target.x86_64-unknown-linux-gnu]
image = "docker.pkg.github.com/meatlink/northstar/x86_64-unknown-linux-gnu:v11"
