---
    name: Build
    on:
      push:
        branches:
          - dpotapov

    jobs:
      build:
        name: Build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - env:
              TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              sudo apt update
              sudo apt install -y gcc
              sudo apt install -y libsodium-dev

              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y | sh
              source $HOME/.cargo/env

              echo "${TOKEN}" | docker login https://docker.pkg.github.com \
                -u meatlink --password-stdin
              
              bundle add rake

              bundle exec rake examples:build
