---
name: Build docker images
on:
  push:
    paths:
      - docker/**

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: shell hello world
        run: |
          echo 'build docker images and push to registry. But what tag should be used?'
