---
name: Build docker images
on:
  push:
    tags:
      - docker-*
    # paths:
    #   - docker/**

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: shell hello world
        run: |
          echo '${github.event}'
          echo 'docker build -t TAG_NEEDED'
