---
name: Build docker images
on:
  push:
    tags:
      - docker-*
    # paths:
    #   - docker/**

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: shell hello world
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="$( echo "${GITHUB_REF}" | sed 's/refs\/tags\/docker-//' )"
          echo "docker build -t ${tag}"
          echo "${TOKEN}" | docker login https://docker.pkg.github.com -u meatlink --password-stdin
          ls
