---
name: Build docker images
on:
  push:
    tags:
      - docker-*
    # paths:
    #   - docker/**

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: shell hello world
        run: |
          tag="$( echo "${GITHUB_REF}" | sed 's/refs\/tags\/docker-//' )"
          echo 'docker build -t "${tag}"'
