---
name: Build docker images
on:
  push:
    tags:
      - docker-*
    # paths:
    #   - docker/**

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: shell hello world
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}"
          echo 'docker build -t TAG_NEEDED'
